"use client";

import { useEffect, useMemo, useState } from "react";

const LINKS = {
  english: "https://forms.gle/9uacvDpxwrxcwGUi8",
  accounting: "https://docs.google.com/forms/d/e/1FAIpQLScgQyKPqdxRP8ty_ZMIN3e7Tx2ohsG4kIAHHbcqE1BVc5D3ag/viewform?usp=header",
  science: "https://forms.gle/gFfqz7fVCSrfAjUM6",
  engineering: "https://forms.gle/rR8i2K4mBzp4AEmS9",
  welfareEmail: "amir.austria@dlsu.edu.ph",
  officialEmail: "ssc@dlsu.edu.ph",
  facebook: "https://www.facebook.com/dlsu.ssc/",
} as const;

type Session = { service: string; category: string; subject: string; date?: string; recurring?: string; time: string; tutor: string; mode?: "Online" | "On-site"; venue?: string; audience?: string; link: string };

const dated = (service:string, category:string, subject:string, tutor:string, link:string, dates:string[], time:string):Session[] => dates.map(date=>({service,category,subject,tutor,link,date,time}));
const sessions: Session[] = [
  {service:"English Language Tutorial",category:"English",subject:"English support for graduate students and employees",recurring:"Tuesday and Friday",time:"6:00–7:30 PM",tutor:"Mr. Allan Villaverde",mode:"Online",audience:"Graduate students and DLSU employees",link:LINKS.english},
  {service:"English Language Tutorial",category:"English",subject:"Grammar and Writing",recurring:"Tuesday and Friday",time:"9:15–10:45 AM",tutor:"Ms. Maria Ana de Guzman",mode:"Online",audience:"SHS, undergraduate students, and employees",link:LINKS.english},
  {service:"English Language Tutorial",category:"English",subject:"Grammar and Writing",recurring:"Wednesday and Thursday",time:"6:00–7:30 PM",tutor:"Dr. Marilou Santos",mode:"Online",audience:"SHS, undergraduate students, and employees",link:LINKS.english},
  {service:"English Language Tutorial",category:"English",subject:"Speaking and Oral Presentation Skills",recurring:"Tuesday and Friday",time:"11:00 AM–12:30 PM",tutor:"Mr. Dennis Villacorta",mode:"Online",audience:"SHS, undergraduate students, and employees",link:LINKS.english},
  {service:"English Language Tutorial",category:"English",subject:"Speaking and Oral Presentation Skills",recurring:"Tuesday",time:"6:00–7:30 PM",tutor:"Ms. Rubie Sajise",mode:"Online",audience:"SHS, undergraduate students, and employees",link:LINKS.english},
  {service:"English Language Tutorial",category:"English",subject:"Speaking and Oral Presentation Skills",recurring:"Friday",time:"9:15–10:45 AM",tutor:"Ms. Rubie Sajise",mode:"On-site",venue:"A1410",audience:"SHS, undergraduate students, and employees",link:LINKS.english},
  ...dated("Accounting Tutorial and Review Classes","Accounting","Special Tutorials for ACCOB 3","",LINKS.accounting,["2026-07-04"],"8:00–9:30 PM"),
  ...dated("Accounting Tutorial and Review Classes","Accounting","Introduction to Accounting and the Accounting Cycle","",LINKS.accounting,["2026-07-06","2026-07-10","2026-07-13"],"6:30–8:00 PM"),
  ...dated("Accounting Tutorial and Review Classes","Accounting","Introduction to Accounting and the Accounting Cycle","",LINKS.accounting,["2026-07-06","2026-07-10","2026-07-13"],"8:30–10:00 PM"),
  ...dated("Accounting Tutorial and Review Classes","Accounting","Accounting for Merchandising","",LINKS.accounting,["2026-07-17","2026-07-20","2026-07-24"],"6:30–8:00 PM"),
  ...dated("Accounting Tutorial and Review Classes","Accounting","Accounting for Merchandising","",LINKS.accounting,["2026-07-17","2026-07-20","2026-07-24"],"8:30–10:00 PM"),
  ...dated("Science Tutorial and Review Classes","Science","Mth101A","Mr. Edward Concepcion",LINKS.science,["2026-07-07","2026-07-10","2026-07-14","2026-07-17","2026-07-21","2026-07-24"],"4:00–5:00 PM"),
  ...dated("Science Tutorial and Review Classes","Science","Organic Chemistry","Dr. Virgilio Ebajo Jr.",LINKS.science,["2026-07-13","2026-07-16","2026-07-20","2026-07-23"],"4:00–5:00 PM"),
  ...dated("Science Tutorial and Review Classes","Science","Systematics","Ms. Sarah Zamudio",LINKS.science,["2026-07-14","2026-07-21"],"10:00–11:00 AM"),
  ...dated("Science Tutorial and Review Classes","Science","Systematics","Ms. Sarah Zamudio",LINKS.science,["2026-07-16","2026-07-23"],"4:00–5:00 PM"),
  ...dated("Science Tutorial and Review Classes","Science","Cell and Molecular Biology","Dr. Paul Benedic Salvador",LINKS.science,["2026-07-15","2026-07-17","2026-07-22","2026-07-24"],"9:30–10:30 AM"),
  {service:"Engineering Tutorial and Review Classes",category:"Engineering",subject:"CALENG2 and CALENG3",recurring:"Wednesday",time:"10:00–11:00 AM",tutor:"Engr. Marc Dylan M. Lipit",link:LINKS.engineering},
  {service:"Engineering Tutorial and Review Classes",category:"Engineering",subject:"CALENG1 and CALENG2",recurring:"Thursday",time:"6:00–7:00 PM",tutor:"Engr. Cary Albert D. Chan",link:LINKS.engineering},
  {service:"Engineering Tutorial and Review Classes",category:"Engineering",subject:"FNDSTAT, DATAENG, and BASCHEM",recurring:"Friday",time:"6:00–7:00 PM",tutor:"Engr. Piolo Gabriel N. Gervacio",link:LINKS.engineering},
  {service:"Engineering Tutorial and Review Classes",category:"Engineering",subject:"FNDMATH",recurring:"Wednesday",time:"9:30–10:30 AM",tutor:"Engr. Jesus Patrick Nuqui",link:LINKS.engineering},
  {service:"Engineering Tutorial and Review Classes",category:"Engineering",subject:"CALENG1 and CALENG3",recurring:"Friday",time:"1:00–2:00 PM",tutor:"Engr. Ithan Jessemar Dollente",link:LINKS.engineering},
];

const services = [
  ["English Language Tutorial","Grammar, writing, speaking, and oral presentation support for specified student groups and employees.","English",LINKS.english],
  ["Accounting Tutorial and Review Classes","Sessions on ACCOB 3, the accounting cycle, and accounting for merchandising.","Accounting",LINKS.accounting],
  ["Science Tutorial and Review Classes","Support for mathematics, organic chemistry, systematics, and cell and molecular biology.","Science",LINKS.science],
  ["Engineering Tutorial and Review Classes","Tutorials for CALENG, FNDSTAT, DATAENG, BASCHEM, and FNDMATH courses.","Engineering",LINKS.engineering],
] as const;

const formatDate=(d:string)=>new Intl.DateTimeFormat("en-PH",{month:"long",day:"numeric",year:"numeric"}).format(new Date(d+"T12:00:00"));
const status=(d?:string)=>{ if(!d)return "Recurring"; const today="2026-07-12"; return d===today?"Today":d>today?"Upcoming":"Completed" };

export default function Home(){
  const [menu,setMenu]=useState(false), [cat,setCat]=useState("All Services"), [query,setQuery]=useState(""), [mode,setMode]=useState("All"), [audience,setAudience]=useState("All"), [dateState,setDateState]=useState("All"), [view,setView]=useState<"cards"|"list">("cards"), [active,setActive]=useState("home");
  useEffect(()=>{const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&setActive(e.target.id)),{rootMargin:"-35% 0px -55%"}); document.querySelectorAll("main section[id]").forEach(x=>obs.observe(x)); return()=>obs.disconnect()},[]);
  const audiences=useMemo(()=>["All",...Array.from(new Set(sessions.map(x=>x.audience).filter(Boolean) as string[]))],[]);
  const filtered=useMemo(()=>sessions.filter(s=>(cat==="All Services"||s.category===cat)&&(mode==="All"||s.mode===mode)&&(audience==="All"||s.audience===audience)&&(dateState==="All"||status(s.date)===dateState)&&(`${s.service} ${s.subject} ${s.tutor} ${s.audience||""}`.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>(a.date||"9999").localeCompare(b.date||"9999")),[cat,query,mode,audience,dateState]);
  const clear=()=>{setCat("All Services");setQuery("");setMode("All");setAudience("All");setDateState("All")};
  const nav=["Home","About","Services","Schedule","Upcoming","Welfare Support","Contact"];
  return <>
    <header className="nav"><a className="brand" href="#home"><span className="sscLogo" role="img" aria-label="Student Success Center logo"/><span><b>Academic Support Hub</b><small>De La Salle University · Student Success Center</small></span></a><button className="menu" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>☰</button><nav className={menu?"open":""} aria-label="Main navigation">{nav.map(n=><a key={n} className={active===n.toLowerCase().replace(" support","")?"active":""} href={`#${n.toLowerCase().replaceAll(" ","-").replace("-support","")}`} onClick={()=>setMenu(false)}>{n}</a>)}<a className="navCta" href="#services">Find Support</a></nav></header>
    <main>
      <section id="home" className="hero"><div className="heroPanel"><div className="heroCopy"><p className="eyebrow">Student Success Center · De La Salle University</p><h1>Support for<br/><em>every step.</em></h1><p className="lead">Find tutorials, review classes, learning support, and student welfare assistance designed to help you persist, progress, and thrive.</p><div className="actions"><a className="primary" href="#services">Explore Support ↗</a><a className="secondary" href="#schedule">View Schedule</a></div></div><div className="brandImage finalHero"><img src="/final.png" alt="Collage of DLSU students studying within the Academic Support Hub step symbol"/></div><div className="servicePills">{["English","Accounting","Science","Engineering","Student Welfare"].map(x=><a key={x} href={x==="Student Welfare"?"#welfare":"#services"}>✦ {x}</a>)}</div></div><div className="heroMeta"><span>Academic Support Hub</span><span>Term 3 · AY 2025–2026</span><span>Helping Lasallians thrive</span></div></section>

      <section id="about" className="about shell"><div><p className="eyebrow green">About the unit</p><h2>Support that begins before a student falls behind.</h2><div className="campusFrame" role="img" aria-label="St. La Salle Hall at De La Salle University"><span>ANIMO<br/>LA SALLE</span></div></div><div className="aboutGrid"><article><span>01</span><h3>More than tutorials</h3><p>The Academic Support Unit uses a tiered, proactive, and student-centered model. Its work includes learning interventions, study skills development, academic coaching, referral and matching, peer-led and faculty-led support, and targeted guidance.</p></article><article><span>02</span><h3>Responsive academic help</h3><p>Through the Lasallian SHiNE Program, the unit offers tutorial and review sessions for high-impact and high-need courses identified through student demand, academic performance, and college or faculty recommendations.</p></article><article><span>03</span><h3>Capacity and partnership</h3><p>Support includes time management, study strategies, exam preparation, academic recovery planning, and learning strategies, delivered with faculty, departments, student organizations, and student support offices.</p></article></div><blockquote>Academic success goes beyond tutorials. It also requires coordinated support, early intervention, student welfare assistance, and partnerships that help students persist, progress, and thrive.</blockquote></section>

      <section id="services" className="services shell"><div className="sectionHead"><div><p className="eyebrow green">Term 3 AY 2025–2026</p><h2>Available academic support</h2></div><p>SSC has identified high-priority courses based on student demand, academic performance, and administrative recommendations.</p></div><div className="serviceGrid">{services.map((s,i)=><article className="serviceCard" key={s[0]}><span className="number">0{i+1}</span><span className="tag">{s[2]}</span><h3>{s[0]}</h3><p>{s[1]}</p><div><a href="#schedule" onClick={()=>setCat(s[2])}>View schedule</a><a className="register" href={s[3]} target="_blank" rel="noopener noreferrer">Register ↗</a></div></article>)}<article className="serviceCard welfareMini"><span className="number">05</span><span className="tag">Welfare Support</span><h3>Lasallian Welfare Program</h3><p>Support addressing financial or material barriers that may affect academic participation and continuity.</p><div><a href="#welfare">Explore support</a></div></article></div></section>

      <section id="schedule" className="schedule"><div className="scheduleImage" role="img" aria-label="Henry Sy Sr. Hall at De La Salle University"><span>YOUR NEXT<br/>STEP STARTS HERE.</span></div><div className="shell"><div className="sectionHead light"><div><p className="eyebrow lime">Session Schedule</p><h2>Find your next session.</h2></div><div className="viewToggle"><button className={view==="cards"?"on":""} onClick={()=>setView("cards")}>Cards</button><button className={view==="list"?"on":""} onClick={()=>setView("list")}>List</button></div></div>{filtered.length===0?<div className="empty"><b>No sessions match your filters.</b><p>Try another keyword or clear the filters to see all available sessions.</p><button onClick={clear}>Clear filters</button></div>:view==="cards"?<div className="sessionGrid">{filtered.map((s,i)=><SessionCard s={s} key={`${s.subject}-${s.date}-${s.time}-${i}`}/>)}</div>:<div className="tableWrap"><table><thead><tr><th>Session</th><th>When</th><th>Tutor</th><th>Mode / audience</th><th></th></tr></thead><tbody>{filtered.map((s,i)=><tr key={i}><td><small>{s.category}</small><b>{s.subject}</b></td><td>{s.date?formatDate(s.date):s.recurring}<br/>{s.time}</td><td>{s.tutor||"Not specified"}</td><td>{[s.mode,s.venue,s.audience].filter(Boolean).join(" · ")||"Not specified"}</td><td><a href={s.link} target="_blank" rel="noopener noreferrer">Register ↗</a></td></tr>)}</tbody></table></div>}</div></section>

      <section id="upcoming" className="upcoming shell"><div className="sectionHead"><div><p className="eyebrow green">In development</p><h2>Upcoming support</h2></div><p>More ways to support Lasallian learning are coming soon.</p></div><div className="upGrid">{[{name:"Filipino Tutorial",icon:"speech"},{name:"STARS: Study Teams for Academic Resilience and Success",icon:"stars"},{name:"Academic Life Management",icon:"plan"}].map((x,i)=><article key={x.name}><div className={`upIcon ${x.icon}`} aria-hidden="true"><i/><i/><i/></div><span>Coming Soon</span><b>0{i+1}</b><h3>{x.name}</h3></article>)}</div></section>

      <section id="welfare" className="welfare"><div className="shell"><div className="welfareIntro"><div><p className="eyebrow lime">Lasallian Welfare Program</p><h2>Support for the barriers beyond the classroom.</h2></div><p>The program forms part of the broader academic support ecosystem by helping address financial or material barriers that may affect a student’s academic participation and continuity.</p></div><div className="welfareGrid"><Welfare title="Student Emergency Health Aid">Emergency or urgent health-related expenses that affect safety, recovery, or the ability to continue studies.</Welfare><Welfare title="Student Life Assistance Program">Short-term support for essential student participation and academic continuity.</Welfare><Welfare title="Student Emergency Relief Fund">Relief following disasters, emergency crises, family shocks, or life-altering accidents.</Welfare></div><a className="primary limeBtn" href={`mailto:${LINKS.welfareEmail}`}>Contact About Welfare Support ↗</a></div></section>

      <section id="contact" className="contact shell"><div className="contactCard"><div className="contactCopy"><p className="eyebrow green">Connect with us</p><h2>Not sure where to begin?</h2><p>Contact the Student Success Center at De La Salle University.</p><div className="actions"><a className="primary" href={`mailto:${LINKS.officialEmail}`}>Email the Student Success Center</a><a className="secondary" href={LINKS.facebook} target="_blank" rel="noopener noreferrer">Visit Our Facebook Page ↗</a></div></div><div className="contactPhoto" role="img" aria-label="Yuchengco Hall at De La Salle University"><span>HERE<br/>WITH YOU.</span></div></div></section>
    </main>
    <footer><div className="footerPhoto" role="img" aria-label="Yuchengco Hall at De La Salle University"><span>Helping Lasallians<br/>persist, progress, and thrive.</span></div><div className="shell footerGrid"><div><span className="footerLogo" role="img" aria-label="Student Success Center logo"/><h3>Student Success Center</h3><p>Academic Support Hub · De La Salle University</p></div><div><h4>Navigate</h4>{nav.slice(1).map(n=><a key={n} href={`#${n.toLowerCase().replaceAll(" ","-").replace("-support","")}`}>{n}</a>)}</div><div><h4>Contact</h4><a href={`mailto:${LINKS.officialEmail}`}>{LINKS.officialEmail}</a><a href={LINKS.facebook} target="_blank" rel="noopener noreferrer">Facebook ↗</a></div></div></footer><a className="top" href="#home" aria-label="Back to top">↑</a>
  </>;
}

function SessionCard({s}:{s:Session}){return <article className="sessionCard"><div><span className={`status ${status(s.date).toLowerCase()}`}>{status(s.date)}</span><span className="category">{s.category}</span></div><h3>{s.subject}</h3><dl><div><dt>When</dt><dd>{s.date?formatDate(s.date):s.recurring}<br/><b>{s.time}</b></dd></div>{s.tutor&&<div><dt>Tutor</dt><dd>{s.tutor}</dd></div>}{(s.mode||s.venue)&&<div><dt>Delivery</dt><dd>{[s.mode,s.venue].filter(Boolean).join(" · ")}</dd></div>}{s.audience&&<div><dt>For</dt><dd>{s.audience}</dd></div>}</dl><a href={s.link} target="_blank" rel="noopener noreferrer">Register for this service ↗</a></article>}
function Welfare({title,children}:{title:string,children:React.ReactNode}){return <article><span>✦</span><h3>{title}</h3><p>{children}</p></article>}
